[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."generate-questions"]
  timeout = 120

[functions."research-company"]
  timeout = 120

[functions."groq-whisper"]
  timeout = 60

# Redirige /apex a la carpeta apex
[[redirects]]
  from = "/apex"
  to = "/apex/index.html"
  status = 200

[[redirects]]
  from = "/apex/*"
  to = "/apex/:splat"
  status = 200
